#spring.application.name=login
#spring.datasource.url=jdbc:mysql://localhost:3306/login
#spring.datasource.username=root
#spring.datasource.password=s1108
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#?severTimezone=Asia/Seoul&characterEncoding=UTF-8
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?severTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_admin
    password: s1108
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create