#spring.application.name=login
#spring.datasource.url=jdbc:mysql://localhost:3306/login
#spring.datasource.username=root
#spring.datasource.password=s1108
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: s1108
    driver-class-name: com.mysql.cj.jdbc.Driver